# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_publicacao_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='resumo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
