# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacao_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
