# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171001_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
