# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171001_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AddField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicao', verbose_name='Imagem'),
        ),
    ]
