# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171002_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/img', verbose_name='Imagem'),
        ),
    ]
