# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171002_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='resumo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
