# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='contato',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
