# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171003_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='image_detalhe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
