# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
